### ISSUE TITLE
cloud start (or any other interaction) fails if you don't have AWS_ACCESS_KEY in ENV even when you explicitly give access_key in pool or cloud block

### ISSUE THREAD

**Issue by contentfree** [auser/poolparty#10]
In your ~/.profile, remove an setting of AWS_ACCESS_KEY and set it explicitly in the pool block of clouds.rb. Or do what I do: At the top of clouds.rb I have:

ENV['AWS_ACCESS_KEY'] = ENV['MY_ACCESS_KEY_ID']
ENV['AWS_SECRET_ACCESS_KEY'] = ENV['MY_SECRET_ACCESS_KEY']
ENV['EC2_PRIVATE_KEY'] = ENV['MY_EC2_PRIVATE_KEY']
ENV['EC2_CERT'] = ENV['MY_EC2_CERT']

Then try running `cloud start`. I get a failure with this backtrace:

/opt/local/lib/ruby/gems/1.8/gems/grempe-amazon-ec2-0.3.7/lib/EC2.rb:116:in `initialize': No :access_key_id provided (EC2::ArgumentError)
        from /Users/user/Open Source/poolparty/bin/../lib/poolparty/net/remoter_bases/ec2/ec2.rb:102:in`new'
        from /Users/user/Open Source/poolparty/bin/../lib/poolparty/net/remoter_bases/ec2/ec2.rb:102:in `ec2'
        from /Users/user/Open Source/poolparty/bin/../lib/poolparty/net/remoter_bases/ec2/ec2.rb:184:in`ec2'
        from /Users/user/Open Source/poolparty/bin/../lib/poolparty/net/remoter_bases/ec2/ec2.rb:109:in `get_instances_description'
        from /Users/user/Open Source/poolparty/bin/../lib/poolparty/net/remoter_bases/ec2/ec2.rb:83:in`describe_instances'
        from /Users/user/Open Source/poolparty/bin/../lib/poolparty/net/remoter/interactive.rb:40:in `_list_of_instances'
        from /Users/user/Open Source/poolparty/bin/../lib/poolparty/net/remoter/interactive.rb:33:in`list_of_instances'
        from /Users/user/Open Source/poolparty/bin/../lib/poolparty/net/remoter/interactive.rb:18:in `nodes'
        from /Users/user/Open Source/poolparty/bin/cloud-start:11
        from /Users/user/Open Source/poolparty/bin/cloud-start:9:in`each'
        from /Users/user/Open Source/poolparty/bin/cloud-start:9

Ideally, you would be able to control poolparty from clouds.rb without relying on what's in your profile or ENV at all.

**Comment by contentfree** [comment]
Looks like I was wrong. Perhaps my .profile hadn't be reload or something.
