### ISSUE TITLE
undefined method rules_values

### ISSUE THREAD

**Issue by pingali** [auser/poolparty#2]
cloud-stats --debug --verbose

-- Using spec at /home/codisc/rails/umanage/clouds.rb

-- In after create

**\* App cloud stats

DEPRECATED:  'master' is deprecated and will be removed in the next major release.

```
  Running . /etc/profile && server-show-stats on master

   /usr/lib/ruby/gems/1.8/gems/auser-poolparty-1.1.5/bin/../lib/poolparty/monitors/../..  /../vendor/gems/dslify/lib/dslify/dslify.rb:52:in `send': undefined method `rules_values' for nil:NilClass (NoMethodError)
    from /usr/lib/ruby/gems/1.8/gems/auser-poolparty-1.1.5/bin/../lib/poolparty/monitors/../../../vendor/gems/dslify/lib/dslify/dslify.rb:52:in `method_missing'
    from /usr/lib/ruby/gems/1.8/gems/auser-poolparty-1.1.5/bin/../lib/poolparty/poolparty/poolparty_base_class.rb:146:in `method_missing'
    from /usr/lib/ruby/gems/1.8/gems/auser-poolparty-1.1.5/bin/../lib/poolparty/monitors/../../../vendor/gems/dslify/lib/dslify/dslify.rb:52:in `send'
    from /usr/lib/ruby/gems/1.8/gems/auser-poolparty-1.1.5/bin/../lib/poolparty/monitors/../../../vendor/gems/dslify/lib/dslify/dslify.rb:52:in `method_missing'
    from /usr/lib/ruby/gems/1.8/gems/auser-poolparty-1.1.5/bin/../lib/poolparty/poolparty/poolparty_base_class.rb:146:in `method_missing'
    from /usr/lib/ruby/gems/1.8/gems/auser-poolparty-1.1.5/bin/../lib/poolparty/poolparty/cloud.rb:55:in `method_missing'
    *** Stats
    from /usr/lib/ruby/gems/1.8/gems/auser-poolparty-1.1.5/bin/server-show-stats:14
    from /usr/lib/ruby/gems/1.8/gems/auser-poolparty-1.1.5/bin/../lib/poolparty /poolparty/poolparty_base_class.rb:32:in `instance_eval'
    from /usr/lib/ruby/gems/1.8/gems/auser-poolparty-1.1.5/bin/../lib/poolparty/poolparty/poolparty_base_class.rb:32:in `run_in_context'
    from /usr/lib/ruby/gems/1.8/gems/auser-poolparty-1.1.5/bin/../lib/poolparty/poolparty/cloud.rb:20:in `with_cloud'
    from /usr/lib/ruby/gems/1.8/gems/auser-poolparty-1.1.5/bin/server-show-stats:12
    from /usr/lib/ruby/gems/1.8/gems/auser-poolparty-1.1.5/bin/server-show-stats:10:in `each'
    from /usr/lib/ruby/gems/1.8/gems/auser-poolparty-1.1.5/bin/server-show-stats:10
    from /usr/bin/server-show-stats:19:in `load'
    from /usr/bin/server-show-stats:19
```

**Comment by auser** [comment]
Fixed.
