### ISSUE TITLE
Crash during cloud-start

### ISSUE THREAD

**Issue by bradphelan** [auser/poolparty#66]
```
Running command: ssh root@ec2-67-202-7-84.compute-1.amazonaws.com -o StrictHostKeyChecking=no -i /home/brad/.ssh/aprico-deploy-db 'GEM_BIN=$(gem env | grep "EXECUTABLE DIRECTORY" | awk "{print \$4}") && $GEM_BIN/chef-solo -j /etc/chef/dna.json -c /etc/chef/solo.rb'
[Wed, 13 Jan 2010 10:00:25 +0000] INFO: Starting Chef Solo Run
/etc/chef/cookbooks/mysql/attributes/server.rb:20:in `from_file': uninitialized constant Chef::Node::Opscode (NameError)
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/cookbook.rb:78:in `load_attributes'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/cookbook.rb:76:in `each'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/cookbook.rb:76:in `load_attributes'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/compile.rb:76:in `load_attributes'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/cookbook_loader.rb:132:in `each'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/cookbook_loader.rb:131:in `each_value'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/cookbook_loader.rb:131:in `each'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/compile.rb:75:in `load_attributes'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/compile.rb:48:in `initialize'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/client.rb:403:in `new'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/client.rb:403:in `converge'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/client.rb:110:in `run_solo'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/application/solo.rb:191:in `run_application'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/application/solo.rb:183:in `loop'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/application/solo.rb:183:in `run_application'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/application.rb:57:in `run'
    from /var/lib/gems/1.8/gems/chef-0.7.16/bin/chef-solo:26
    from /var/lib/gems/1.8/bin/chef-solo:19:in `load'
    from /var/lib/gems/1.8/bin/chef-solo:19
  running on CloudProviders::Ec2
  for cloud: worker
  minimum_instances: 1
  maximum_instances: 2
  security_groups: aprico-deploy-worker
  using keypair: aprico-deploy-worker
```

**Comment by bradphelan** [comment]
```
root@ip-10-250-6-34:~# GEM_BIN=$(gem env | grep "EXECUTABLE DIRECTORY" | awk "{print \$4}") && $GEM_BIN/chef-solo -j /etc/chef/dna.json -c /etc/chef/solo.rb
[Wed, 13 Jan 2010 10:08:26 +0000] INFO: Starting Chef Solo Run
/etc/chef/cookbooks/mysql/attributes/server.rb:20:in `from_file': uninitialized constant Chef::Node::Opscode (NameError)
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/cookbook.rb:78:in `load_attributes'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/cookbook.rb:76:in `each'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/cookbook.rb:76:in `load_attributes'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/compile.rb:76:in `load_attributes'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/cookbook_loader.rb:132:in `each'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/cookbook_loader.rb:131:in `each_value'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/cookbook_loader.rb:131:in `each'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/compile.rb:75:in `load_attributes'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/compile.rb:48:in `initialize'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/client.rb:403:in `new'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/client.rb:403:in `converge'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/client.rb:110:in `run_solo'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/application/solo.rb:191:in `run_application'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/application/solo.rb:183:in `loop'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/application/solo.rb:183:in `run_application'
    from /var/lib/gems/1.8/gems/chef-0.7.16/lib/chef/application.rb:57:in `run'
    from /var/lib/gems/1.8/gems/chef-0.7.16/bin/chef-solo:26
    from /var/lib/gems/1.8/bin/chef-solo:19:in `load'
    from /var/lib/gems/1.8/bin/chef-solo:19
```

**Comment by bradphelan** [comment]
```
root@ip-10-250-6-34:~# gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 1.3.1
  - RUBY VERSION: 1.8.7 (2008-08-11 patchlevel 72) [i486-linux]
  - INSTALLATION DIRECTORY: /var/lib/gems/1.8
  - RUBY EXECUTABLE: /usr/bin/ruby1.8
  - EXECUTABLE DIRECTORY: /var/lib/gems/1.8/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86-linux
  - GEM PATHS:
     - /var/lib/gems/1.8
     - /root/.gem/ruby/1.8
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :benchmark => false
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["http://gems.rubyforge.org/", "http://gems.opscode.com"]
  - REMOTE SOURCES:
     - http://gems.rubyforge.org/
     - http://gems.opscode.com
root@ip-10-250-6-34:~# 
```

**Comment by auser** [comment]
User issue. Require the OpenSSL cookbook
