### ISSUE TITLE
poolparty/chef.rb [node_bootstrapped?]: private method `chomp' called for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by hedgehog** [auser/poolparty#77]
Using this clouds.rb
http://pastie.org/906974

```
$cloud-configure
<snip>
sent 16046 bytes  received 6432 bytes  4086.91 bytes/sec
total size is 357624  speedup is 15.91
ssh_exchange_identification: Connection closed by remote host
/home/hedge/.rvm/gems/ruby-1.8.7-p248/gems/poolparty-1.6.8/bin/../lib/poolparty/chef.rb:104:in `node_bootstrapped?': private method `chomp' called for nil:NilClass (NoMethodError)
    from /home/hedge/.rvm/gems/ruby-1.8.7-p248/gems/poolparty-1.6.8/bin/../lib/poolparty/chef.rb:108:in `node_bootstrap!'
    from /home/hedge/.rvm/gems/ruby-1.8.7-p248/gems/poolparty-1.6.8/bin/../lib/cloud_providers/remote_instance.rb:46:in `bootstrap_chef!'
    from /home/hedge/.rvm/gems/ruby-1.8.7-p248/gems/poolparty-1.6.8/bin/../lib/cloud_providers/ec2/ec2.rb:250:in `bootstrap_nodes!'
    from /home/hedge/.rvm/gems/ruby-1.8.7-p248/gems/poolparty-1.6.8/bin/../lib/cloud_providers/ec2/ec2.rb:246:in `each'
    from /home/hedge/.rvm/gems/ruby-1.8.7-p248/gems/poolparty-1.6.8/bin/../lib/cloud_providers/ec2/ec2.rb:246:in `bootstrap_nodes!'
    from /home/hedge/.rvm/gems/ruby-1.8.7-p248/gems/poolparty-1.6.8/bin/../lib/cloud_providers/ec2/ec2.rb:259:in `configure_nodes!'
    from /home/hedge/.rvm/gems/ruby-1.8.7-p248/gems/poolparty-1.6.8/bin/../lib/poolparty/cloud.rb:190:in `configure!'
    from /home/hedge/.rvm/gems/ruby-1.8.7-p248/gems/poolparty-1.6.8/bin/cloud-configure:23
    from /home/hedge/.rvm/gems/ruby-1.8.7-p248/gems/poolparty-1.6.8/bin/cloud-configure:21:in `each'
    from /home/hedge/.rvm/gems/ruby-1.8.7-p248/gems/poolparty-1.6.8/bin/cloud-configure:21
    from /home/hedge/.rvm/gems/ruby-1.8.7-p248/gems/poolparty-1.6.8/vendor/gems/git-style-binaries/lib/git-style-binary/command.rb:114:in `call'
    from /home/hedge/.rvm/gems/ruby-1.8.7-p248/gems/poolparty-1.6.8/vendor/gems/git-style-binaries/lib/git-style-binary/command.rb:114:in `call_parser_run_block'
    from /home/hedge/.rvm/gems/ruby-1.8.7-p248/gems/poolparty-1.6.8/vendor/gems/git-style-binaries/lib/git-style-binary/command.rb:74:in `run'
    from /home/hedge/.rvm/gems/ruby-1.8.7-p248/gems/poolparty-1.6.8/vendor/gems/git-style-binaries/lib/git-style-binary/autorunner.rb:16:in `run'
    from /home/hedge/.rvm/gems/ruby-1.8.7-p248/gems/poolparty-1.6.8/vendor/gems/git-style-binaries/lib/git-style-binary/autorunner.rb:8:in `run'
    from /home/hedge/.rvm/gems/ruby-1.8.7-p248/gems/poolparty-1.6.8/vendor/gems/git-style-binaries/lib/git-style-binary.rb:85
    from /home/hedge/.rvm/gems/ruby-1.8.7-p248/bin/cloud-configure:19
```

**Comment by hedgehog** [comment]
This error is eliminated by upgrading to Poolparty version `1.6.9`.
